version: '3.1' 

services:
  backend:
    image: node:16.15.1-alpine
    ports:
      - "3001:3001"
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: backend
    tty: true
    stdin_open: true
    command: "yarn dev"
    restart: always
    depends_on:
      - db
    environment:
      DEV_DB_USERNAME: root
      DEV_DB_PASSWORD: password
      DEV_DB_HOST: db
      DEV_DB_PORT: 3306
      DEV_DB_DATABASE: comcad
      DEV_DB_DIALECT: mysql
      NODE_ENV: development
      API_PORT: 3001
      JWT_SECRET: d41552e7ecffe76715d121cd1b6da281
  db:
    container_name: db
    image: mysql:8
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: comcad_net